### ISSUE TITLE
Doesn't actually install with Py3.3+

### ISSUE THREAD

**Issue by jacobsvante** [salsita/flask-mime-encoders#1]
When trying to install with pip:

```
File "/private/var/folders/_m/30cnr5gx5_v7c0x9j6ht1_hh0000gn/T/pip-build-fml8qgep/Flask-MIME-encoders/setup.py", line 134
        except ImportError, e:
```

**Comment by iki** [comment]
Thanks for reporting, fixed in 47fdc4e9e1edb8e9a9990c6195e02609b010de1e ([v0.1.2](https://github.com/salsita/flask-mime-encoders/tree/v0.1.2)).
